homework-02
Otus-DevOps-2020-11/yetoneya_infra pull request #4
Opened 2020-12-20 17:35 UTC by yetoneya

2020-12-22 05:49 UTC, mrgreyves requested changes
Здравствуйте! Проверил ваше дз. Все домашние задания нужно выполнять в репозиториях созданных для вас. Так же если это дз play-travis то в репозитории не хватает файлов. ДЗ возвращаю на доработку.

2020-12-22 18:54 UTC, yetoneya commented
> Здравствуйте! Проверил ваше дз. Все домашние задания нужно выполнять в репозиториях созданных для вас. Так же если это дз play-travis то в репозитории не хватает файлов. ДЗ возвращаю на доработку.

 Permission to Otus-DevOps-2020-11/yetoneya_infra.git denied to yetoneya?

2020-12-23 13:32 UTC, mrgreyves requested changes
Здравствуйте! Еще раз проверил ваше дз. Разрешения на пуш не было потому что вы не приняли приглашение. Добавил вам права руками. Так же нужно добавить описание к пр и переделать название ветки из которой делается пр. ДЗ возвращаю на доработку.

2020-12-23 13:32 UTC, mrgreyves commented on .travis.yml
> +- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-11/run.sh | bashdist: trusty
Ошибка в строке

2020-12-25 08:37 UTC, closed without merging