Play travis
Otus-DevOps-2020-11/yetoneya_infra pull request #6
Opened 2020-12-25 12:49 UTC by yetoneya

2020-12-28 05:54 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. В файле travis.yml ошибка, свертесь с методичкой. ДЗ возвращаю на доработку.

2020-12-28 05:54 UTC, mrgreyves commented on .travis.yml
> +- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-11/run.sh | bashdist: trusty
Ошибка!

2020-12-30 07:22 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2020-12-30 09:58 UTC, yetoneya commented on .travis.yml
> +- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-11/run.sh | bashdist: trusty
исправила

2020-12-30 09:58 UTC, merged